"""update max len in column for Product model

Revision ID: 8aaa44d3f5e4
Revises: 1dc158a20dcb
Create Date: 2026-03-29 14:48:20.734012

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8aaa44d3f5e4"
down_revision: Union[str, Sequence[str], None] = "1dc158a20dcb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "name",
        existing_type=sa.VARCHAR(length=300),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=300),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
